defaults: &defaults
  encoding: unicode
  adapter: postgresql
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>

development:
  <<: *defaults
  database: <%= ENV['DATABASE_NAME'] + '_development' %>

test:
  <<: *defaults
  database: <%= ENV['DATABASE_NAME'] + '_test' %>

staging:
  <<: *defaults
